### ISSUE TITLE
access_denied

### ISSUE THREAD

**Issue by bbarthel** [aws-samples/ask-around-me#2]
When I try running the application locally and click the log in button, the url in the browser has the following value:

http://localhost:8080/?error=access_denied&error_description=Service%20not%20found%3A%20https%3A%2F%2Fauth0-jwt-authorizer&state=Mm5Fdi1mVjNvdldwY1p0dGNNeU5tcDlPblJqOW14Mi1fNmVDV213YlljVA%3D%3D

=======================
Debug window has this info:

asyncToGenerator.js?1da1:6 Uncaught (in promise) {error: "access_denied", error_description: "Service not found: https://auth0-jwt-authorizer", state: "MU9sfkljVUlQVElVSmR6Q05KRzVQbjhDejBfYS1yamxnSjUyQ2gwYl80TQ=="}error: "access_denied"error_description: "Service not found: https://auth0-jwt-authorizer"state: "MU9sfkljVUlQVElVSmR6Q05KRzVQbjhDejBfYS1yamxnSjUyQ2gwYl80TQ=="__proto__: Object
asyncGeneratorStep @ asyncToGenerator.js?1da1:6
_throw @ asyncToGenerator.js?1da1:29
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
updateResults @ HomeView.vue?409a:166
navigator.geolocation.getCurrentPosition.enableHighAccuracy @ HomeView.vue?409a:150
stream.js?553e:64 WebSocket connection to 'wss://no-credentials-available/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
=======================================

Any thoughts /  suggestions?

Thanks,

Bill

**Comment by jbesw** [comment]
Hi Bill! This looks like the auth_config.json may not contain the correct values, or you have different values configured in your Auth0 account. Verify that your "audience" value in the Auth0 configuration is set to https://auth0-jwt-authorizer. HTH!

**Comment by bbarthel** [comment]
Shouldn't that be https://auth0-jwt-authorizer?  Also, do you need to configure anything in auth0.com for the audience?

**Comment by jbesw** [comment]
Yes, updated - sorry about that. The important thing about the audience is to ensure that the API Gateway audience matches the Auth0 audience exactly. If you log out the token to the console, you can use JWT.IO to decode the token and see what has been encoded. This is extremely useful for catching minor issues that otherwise stop everything from working.

I used this QuickStart process (https://auth0.com/docs/quickstart/spa/vuejs/01-login) in the app, so if you follow these instructions, it should set you up with a working Auth0 application. I'm also going to create some videos shortly that walkthrough the process to make it clearer. I hope this helps.

**Comment by bbarthel** [comment]
Hi James.  I followed the QuickStart process and got that application to work ... in that example, the auth_config.json does not have the "audience" entry.  Any other ideas?
![image](https://user-images.githubusercontent.com/4349780/84808369-39703480-afce-11ea-93a4-3e453303390f.png)

**Comment by bbarthel** [comment]
Hi James. I followed the QuickStart process and got that application to work ... in that example, the auth_config.json does not have the "audience" entry. Any other ideas?
![image](https://user-images.githubusercontent.com/4349780/84808524-6886a600-afce-11ea-93a6-a06cd2e4f5d7.png)

auth_config.json:
{
  "domain": "dev--vm0t8mn.auth0.com",
  "clientId": "Cf1OEFal6eV9M14KJClw94Kk0AS0DGmt",
  "audience": "https://auth0-jwt-authorizer"
}

In auth0 logs:
{
  "date": "2020-06-16T18:55:34.953Z",
  "type": "fsa",
  "description": "Service not found: https://auth0-jwt-authorizer",
  "client_id": "Cf1OEFal6eV9M14KJClw94Kk0AS0DGmt",
  "client_name": "AskAroundMe",
  "ip": "xxx.xxx.xxx.xxx",
  "user_agent": "Chrome 83.0.4103 / Windows 10.0.0",
  "details": {
    "body": {},
    "qs": {
      "client_id": "Cf1OEFal6eV9M14KJClw94Kk0AS0DGmt",
      "audience": "https://auth0-jwt-authorizer",
      "redirect_uri": "http://localhost:8080",
      "scope": "openid profile email",
      "response_type": "code",
      "response_mode": "web_message",
      "state": "QkNOUUFEVGJ1WXNGTVlKTFRLVThJMjhCemViTXctUFBtWTdZaTlOWE5rcg==",
      "nonce": "dWtSaVNoMmRFQkZZbFhmVzVmV1k0QXdxdTE3MXU5ME55S3NFOXA4RUFrLg==",
      "code_challenge": "F5UBvCBf1mQw-b51KJaOw1V-bZZSmmBsF28WOP5rNmA",
      "code_challenge_method": "S256",
      "prompt": "none",
      "auth0Client": "eyJuYW1lIjoiYXV0aDAtc3BhLWpzIiwidmVyc2lvbiI6IjEuNy4wIn0="
    },
    "connection": null,
    "error": {
      "message": "Service not found: https://auth0-jwt-authorizer",
      "oauthError": "access_denied",
      "type": "oauth-authorization"
    }
  },
  "hostname": "dev--vm0t8mn.auth0.com",
  "auth0_client": {
    "name": "auth0-spa-js",
    "version": "1.7.0"
  },
  "log_id": "90020200616185535946000540988956475421880810879613665346",
  "_id": "90020200616185535946000540988956475421880810879613665346",
  "isMobile": false
}

**Comment by jbesw** [comment]
The QuickStart has a part 2 link that takes you to here - https://auth0.com/docs/quickstart/spa/vuejs/02-calling-an-api. This is where the audience is set up.

You should have a default API setup - if not, I would recommend creating one. You'll see this in the APIs section - 
![image](https://user-images.githubusercontent.com/24660852/84818276-413ad380-afe4-11ea-8d49-54a15a2107b6.png). 

Unfortunately this is hard to troubleshoot since it happens in the Auth0 component before my code gets going, but hopefully this helps figure it out.

**Comment by bbarthel** [comment]
That was the missing link!  Thanks James!

**Comment by jbesw** [comment]
I just figured it out too! I set up a new Auth0 account and was able to repro the error.

I'll make some changes to the instructions to make this clearer. Thanks for wading through the process with me!
